a, b, i, j, x, y = map(float, input().split())
hasil = (a-b)*i/j-(x+y) 
print("%.3f" %(hasil))
a, b= map(float, input().split())
i, j= map(float, input().split())
x, y= map(float, input().split())
hasil = (a-b)*i/j-(x+y)
print("%.3f" %(hasil))